/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface BlogBlog {
  body: string;
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  id: Generated<string>;
  last_modified: Generated<ColumnType<string, string | string, Date | string> | null>;
  state: number;
  title: string;
  user_id: string;
}

export interface BlogBlogComment {
  blog_id: string;
  content: string;
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  id: Generated<string>;
  user_id: string | null;
}

export interface BlogBlogState {
  id: Generated<number>;
  name: string;
}

export interface BlogUserUser {
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  email: string;
  firstname: string;
  id: Generated<string>;
  last_modified: ColumnType<string, string | string, Date | string> | null;
  lastname: string;
  password_hashed: string | null;
}

export interface DB {
  "blog_user.user": BlogUserUser;
  "blog.blog": BlogBlog;
  "blog.blog_comment": BlogBlogComment;
  "blog.blog_state": BlogBlogState;
}
